### ISSUE TITLE
SIMPLIFY - dry css

### ISSUE THREAD

**Issue by franfranfranfran** [pato13/prj-rev-bwfs-tea-cozy#4]
https://github.com/pato13/prj-rev-bwfs-tea-cozy/blob/master/teacozy/resources/css/styles.css#L8-L10

.top header would select a header element inside something with a class of top. does this selector or the styling inside this block add anything to the page? try not to leave in unused or unwanted bits of styling as they can only lead to confusion / frustration down the line.

**Comment by pato13** [comment]
Thank you!
