### ISSUE TITLE
SUBTLETY - flex display / flex wrap

### ISSUE THREAD

**Issue by franfranfranfran** [pato13/prj-rev-bwfs-tea-cozy#5]
https://github.com/pato13/prj-rev-bwfs-tea-cozy/blob/master/teacozy/index.html#L52-L87

excellent use of flex display to line the elements up in this section. consider making use of flex wrap to avoid having to use two separate sections / to let flex do the work of creating two rows for you. more info can be found here - https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap

**Comment by pato13** [comment]
Thank you!
