### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [pato13/prj-rev-bwfs-tea-cozy#6]
**GRADE**: Meets Expectations

**SUMMARY**: Great job on this project! The page itself looks great and you did an excellent job keeping your project folder organized and your html / css neat and organized using consistent indentation. Good use of flex display throughout your project as well.

   Behind the scenes in your css, try make sure to only leave in code that is necessary to the styling of the page. Leaving in extra unused code can only lead to confusion and frustration down the line. Also in your css, try to make use of some short descriptive comments  to label specific chunks that belong to sections on the page. This will help to further organize and increase the readability of your css. 

   From here you are in a great place to explore what Bootstrap has to offer. Here's some more info on how to create a flashier navigation bar by including Bootstrap in your project - https://v4-alpha.getbootstrap.com/components/navbar/

Keep up the great work!

**Comment by pato13** [comment]
Thank you for your comment. I really help me to enhance my project.
